
## Request
# Constants
uint8 IDLE = 0
uint8 TEACH = 1
uint8 REPEAT = 2
uint8 MERGE = 3
uint8 LOCALIZE = 4
uint8 OTHER = 5 # testing only
# Target goal type
uint8 target
# List of keypoints that need to be in the path
uint64[] path
# Center vertex for relocalization/merge
uint64 vertex
# Duration to wait before/after goal start/completion
builtin_interfaces/Duration pause_before
builtin_interfaces/Duration pause_after
---
## Result
# Constants
uint8 SUCCESS = 0
uint8 TIMEOUT = 1
uint8 PATH_INVALID = 2
uint8 EXCEPTION = 3
uint8 UNINITIALIZED = 4
uint8 UNKNOWN_GOAL = 5
uint8 USER_INTERRUPT = 6

uint8 return_code
---
## Feedback
# Progress tracker
bool in_progress
float64 percent_complete
# Is the robot waiting before/after a goal?
bool waiting
