/**:
  ros__parameters:
    tactic:
      chain:
        alpha: 0.0
    path_planning:
      bicycle_mpc:
        type: bicycle_mpc
      bicycle_mpc_follower:
        type: bicycle_mpc_follower
      follow_distance: 1.5
      distance_margin: 0.5
      waypoint_selection: euclidean
      longitudinal_control:
        kp: 2.0
        ki: 0.5
        kd: 0.0
/mr_green/vtr/navigator:
  ros__parameters:
   path_planning:
    leader_namespace:
      /prof_plum 
/prof_plum/vtr/navigator:
  ros__parameters:
   path_planning:
    leader_namespace:
      /mr_green 

    
