/**:
  ros__parameters:
    robot_frame: echo/base_link
    env_info_topic: echo/env_info
    gyro_frame: echo/ouster_front_imu
    lidar_frame: echo/ouster_front_lidar
    lidar_topic: /echo/ouster_front/points
    path_planning:
      type: bicycle_mpc
      follow_distance: 4.15
      distance_margin: 1.0
      leader_namespace: /foxtrot
      waypoint_selection: euclidean
    log_enabled:
      #- navigation
      #- navigation.graph_map_server
      #- navigation.command
        # tactic
      #- tactic
      #- tactic.pipeline
      - tactic.module
      #- tactic.module.live_mem_manager
      #- tactic.module.graph_mem_manager
      #- mission.state_machine
      #- mission.server
        # planner manager
      - cbit.control
      #- cbit.debug
      #- cbit.path_planning
        # mpc
      - mpc.speed_scheduler
      - mpc.debug
      - mpc.solver
      - mpc.follower
      #- mpc.follower.target
