/**:
  ros__parameters:
    robot_frame: echo/base_link
    env_info_topic: echo/env_info
    gyro_frame: echo/ouster_front_imu
    lidar_frame: echo/ouster_front_lidar
    lidar_topic: /echo/ouster_front/points