/**:
  ros__parameters:
    path_planning:
      type: unicycle_mpc_follower
      follow_distance: 3.0
      distance_margin: 100.0
      leader_path_topic: /miss_scarlet/vtr/mpc_prediction
      waypoint_selection: leader_vel
    log_enabled:
      #- navigation
      #- navigation.graph_map_server
      #- navigation.command
        # tactic
      #- tactic
      #- tactic.pipeline
      - tactic.module
      #- tactic.module.live_mem_manager
      #- tactic.module.graph_mem_manager
      #- mission.state_machine
      #- mission.server
        # planner manager
      #- cbit.control
      #- cbit.debug
      #- cbit.path_planning
      #- cbit.obstacle_filtering
      #- grizzly_controller_tests.cbit
        # mpc
      - mpc.speed_scheduler
      - mpc.debug
      - mpc.solver
      - mpc.follower
        # path planner
      #- cbit_planner.path_planning
        # pose graph
      #- pose_graph
        # lidar pipeline
      #- lidar.pipeline
      #- lidar.honeycomb_converter
      #- lidar.preprocessing
      #- lidar.odometry_icp
      #- lidar.odometry_map_maintenance
      #- lidar.vertex_test
      #- lidar.localization_map_recall
      #- lidar.localization_icp
      #- lidar.intra_exp_merging
      #- lidar.dynamic_detection
      #- lidar.inter_exp_merging
      #- lidar.ground_extraction
      #- lidar.obstacle_detection
      #- lidar.terrain_assessment
