/**:
  ros__parameters:
    path_planning:
      type: bicycle_mpc_follower
      follow_distance: 1.5
      distance_margin: 0.25
      leader_namespace: /miss_scarlet
      waypoint_selection: leader_vel
      mpc:
        q_dist: 5.0
        q_y: 0.0
        q_x: 10.0
        wheelbase: 0.65
    log_enabled:
      #- navigation
      #- navigation.graph_map_server
      #- navigation.command
        # tactic
      #- tactic
      #- tactic.pipeline
      - tactic.module
      #- tactic.module.live_mem_manager
      #- tactic.module.graph_mem_manager
      #- mission.state_machine
      #- mission.server
        # planner manager
      - cbit.control
      #- cbit.debug
      #- cbit.path_planning
        # mpc
      - mpc.speed_scheduler
      - mpc.debug
      - mpc.solver
      - mpc.follower
        # path planner
      #- cbit_planner.path_planning
        # pose graph
      #- pose_graph
        # lidar pipeline
      #- lidar.pipeline
      #- lidar.preprocessing
      - lidar.odometry_icp
      #- lidar.odometry_map_maintenance
      #- lidar.vertex_test
      #- lidar.localization_map_recall
      - lidar.localization_icp
      #- lidar.intra_exp_merging
      #- lidar.inter_exp_merging
      - lidar.leader_locator
    pipeline:
      preprocessing:
        - conversion
        - filtering
        - locate_leader
    preprocessing:
      locate_leader:
        type: lidar.leader_locator
        maximum_distance: 5.0
        minimum_distance: 0.0
        intensity_threshold: 10000.0
    
