 /**:
  ros__parameters:
  ############ system configuration ############
    log_debug: false
    robot_frame: base_link
    radar_frame: navtech
    radar_topic: /navtech/b_scan_msg
    gyro_frame: vn100
    gyro_topic: /vn100/data_raw
    gyro_bias: -0.0159328971630528















