/**:
  ros__parameters:
    robot_frame: foxtrot/base_link
    lidar_frame: foxtrot/ouster_back_lidar
    lidar_topic: /foxtrot/ouster_back/points
    tactic:
      chain:
        alpha: 0.0
    path_planning:
      type: bicycle_mpc_follower
      follow_distance: 4.35
      distance_margin: 1.0
      leader_namespace: /echo
      waypoint_selection: euclidean
    log_enabled:
      #- navigation
      #- navigation.graph_map_server
      #- navigation.command
        # tactic
      #- tactic
      #- tactic.pipeline
      - tactic.module
      #- tactic.module.live_mem_manager
      #- tactic.module.graph_mem_manager
      #- mission.state_machine
      #- mission.server
        # planner manager
      - cbit.control
      #- cbit.debug
      #- cbit.path_planning
        # mpc
      - mpc.speed_scheduler
      - mpc.debug
      - mpc.solver
      - mpc.follower
      #- mpc.follower.target

    # pipeline:
    #   preprocessing:
    #     - conversion
    #     - filtering
    #     - locate_leader
    # preprocessing:
    #   locate_leader:
    #     type: lidar.leader_locator
    #     maximum_distance: 5.0
    #     minimum_distance: 0.0
    #     intensity_threshold: 10000.0
    #     publish: true