 /**:
  ros__parameters:
  ############ system configuration ############
    log_to_file: true
    log_debug: true
    log_enabled:
      # - navigation
      - radar.pipeline
      # - navigation.sensor_input
      - radar.navtech_extractor
      - radar.odometry_icp
      - tactic
      - tactic.pipeline
      - tactic.module
      - path_planning.cbit
      - mpc.debug
      - cbit.control
    robot_frame: base_link
    env_info_topic: env_info
    radar_frame: navtech_base #navtech_base
    radar_topic: /radar_data/b_scan_msg
    gyro_topic: /ouster/imu
    queue_size: 1
    graph_map:
      origin_lat: 43.7822 # UTIAS: 43.78220
      origin_lng: -79.4661 # UTIAS: -79.4661
      origin_theta: 1.3
      scale: 1.0
    # Added Tactical Params
    tactic:
      enable_parallelization: true
      preprocessing_skippable: false
      odometry_mapping_skippable: false
      localization_skippable: false
      task_queue_num_threads: 1
      task_queue_size: -1

      route_completion_translation_threshold: 0.5

      chain:
        min_cusp_distance: 1.5
        angle_weight: 7.0
        search_depth: 5
        search_back_depth: 10
        distance_warning: 5.0
      save_odometry_result: true
      save_localization_result: true
      visualize: true
      rviz_loc_path_offset:
        - 0.0
        - 0.0
        - 0.0                                                                                                                                                                  
    ############ pipeline configuration ############
    pipeline:
      type: radar
      preprocessing: 
        - conversion
        - filtering
      odometry:
        - gyro
        - preintegration
        - icp
        - mapping
        - vertex_test
        - memory
      localization: 
        - recall
        - icp
        - memory
      submap_translation_threshold: 1.5
      submap_rotation_threshold: 30.0
    preprocessing:
      conversion:
        type: radar.RAS3_extractor
        radar_resolution: 0.040308 # 0307827  # RAS3 0.161231 #0.044
        detector: modified_cacfar # choose detector \in (kstrongest, cen2018, cacfar, oscfar, modified_cacfar)
        minr: 1.0 # mininum detection distance
        maxr: 72.0 # maximum detection distance
        # TODO: make cart_resolution an integer mult of radar_resolution
        cart_resolution: 0.2384 # m/pixel of BEV Cartesian radar image
        beta: 0.00 # Doppler correction factor (set to 0 to turn this off)
        range_offset: -0.220240  # range offset in meters
        kstrong:
          kstrong: 12 # k-strongest per azimuth to retain
          threshold2: 0.0 # threshold for k-strongest (mult of mean)
          threshold3: 0.216 # treshold for k-strongest (constant)
        cen2018:
          zq: 2.5
          sigma: 8
        cacfar:
          width: 41
          guard: 2
          threshold: 1.0
          threshold2: 0.0 # cfar: mult of mean, T = threshold * Z + threshold2 * mean + threshold3
          threshold3: 0.08
        oscfar:
          width: 41
          guard: 0
          kstat: 20 # used in oscfar, kth statistic to return in window
          threshold: 1.0
          threshold2: 0.0 # cfar: mult of mean, T = threshold * Z + threshold2 * mean + threshold3
          threshold3: 0.07
        modified_cacfar:
          width: 137 # Old: 101, New: 41
          guard: 7 # Old: 5, New: 2
          threshold: 0.55 # Old: 0.2, New: 1.0 # was 0.7
          threshold2: 0.0 # Old: 4.0, New: 0.0 cfar: mult of mean, T = threshold * Z + threshold2 * mean + threshold3
          threshold3: 0.20 # Old: 0.0, New: 0.08 # was 0.23

        visualize: true

      filtering:
        type: radar.preprocessing

        num_threads: 8

        voxel_downsample: false
        frame_voxel_size: 1.0

        window_size: 3.0 # number of neighboring azimuths used to compute line normal
        aximuth_res: 0.015707963267948967 # azimuth resolution in radians (0.1 in degree), giveng M=400
        rho_scale: 1.0 # when finding neighbors, set rho to log(rho) / rho_scale

        num_sample_linearity: 5000 # max number of sample after filtering based on linearity
        min_linearity_score: -1.0 # min linearity score (negative value means no filtering)

        visualize: true

    odometry:
      icp:
        type: radar.odometry_icp

        # continuous time estimation
        use_trajectory_estimation: true
        traj_num_extra_states: 0
        traj_lock_prev_pose: true
        traj_lock_prev_vel: false
        traj_qc_diag: [1.0, 0.0001, 0.0001, 0.0001, 0.0001, 0.001]

        # ICP parameters # TOTUNE
        num_threads: 8
        first_num_steps: 2
        initial_max_iter: 4
        initial_max_pairing_dist: 5.0
        initial_max_planar_dist: 5.0
        refined_max_iter: 1000
        refined_max_pairing_dist: 5.0
        refined_max_planar_dist: 5.0
        averaging_num_steps: 5
        huber_delta: 1.0

        # steam parameters #TOTUNE
        verbose: false
        max_iterations: 2

        # threshold #TOTUNE
        min_matched_ratio: 0.2

        visualize: true

      mapping:
        type: radar.odometry_map_maintenance

        map_voxel_size: 0.5

        crop_range_front: 80.0
        back_over_front_ratio: 1.0

        point_life_time: 3.0

        visualize: true

      vertex_test:
        type: radar.vertex_test

        max_translation: 0.3
        max_rotation: 10.0

      memory:
        type: "live_mem_manager"

        window_size: 5 # unload data older than this many keyframes

    localization:
      recall:
        type: radar.localization_map_recall

        map_version: "pointmap"

        visualize: true

      icp:
        type: radar.localization_icp

        use_pose_prior: true
        # ICP parameters #TO TUNE
        num_threads: 8
        first_num_steps: 2
        initial_max_iter: 4
        initial_max_pairing_dist: 5.0
        initial_max_planar_dist: 5.0
        refined_max_iter: 1000
        refined_max_pairing_dist: 5.0
        refined_max_planar_dist: 5.0
        averaging_num_steps: 5
        huber_delta: 1.0

        # steam parameters #TOTUNE
        verbose: false
        max_iterations: 2

        # threshold #TOTUNE
        min_matched_ratio: 0.1

      memory:
        type: "graph_mem_manager"

        vertex_life_span: 5
        window_size: 3

    path_planning:
      type: cbit # cbit for obstacle free path tracker, cbit.lidar for obstacle avoidance version
      control_period: 100 # ms
      cbit:
        obstacle_avoidance: false
        obs_padding: 0.0
        curv_to_euclid_discretization: 10
        sliding_window_width: 12.0
        sliding_window_freespace_padding: 0.5
        corridor_resolution: 0.2
        state_update_freq: 2.0
        update_state: true
        rand_seed: 1

        # Planner Tuning Params
        initial_samples: 400
        batch_samples: 200
        pre_seed_resolution: 0.5
        alpha: 0.25
        q_max: 2.5
        frame_interval: 50
        iter_max: 10000000
        eta: 1.0
        rad_m_exhange: 1.00
        initial_exp_rad: 0.75
        extrapolation: false
        incremental_plotting: false
        plotting: true
      costmap:
        costmap_filter_value: 0.01
        costmap_history: 15 # Note I dont think im actually using this one anymore, am using the one in the change detection v3 now

      mpc:
        # Controller Params
        extrapolate_robot_pose: false
        mpc_verbosity: false
        forward_vel: 0.75
        max_lin_vel: 1.0
        max_ang_vel: 0.25
        robot_linear_velocity_scale: 1.0 # Used to scale the output twist linear velocity messages by some constant factor to compensate internal low level control miscalibration
        robot_angular_velocity_scale: 1.0 # Used to scale the output twist angular velocity messages by some constant factor to compensate internal low level control miscalibration

        vehicle_model: "unicycle"

        # Misc
        command_history_length: 100
