/**:
  ros__parameters:
    log_enabled:
      - lidar.perspective
      - navigation.sensor_input
      - tactic.pipeline
      - tactic.module

        # pose graph
      #- pose_graph

        # lidar pipeline
      - lidar.pipeline
      - torch
    tactic:
      localization_skippable: true
    pipeline:
      localization:
        - recall
        - icp
        - safe_corridor
        - segmentation
        - memory

    localization:
      segmentation:
        type: lidar.SAM
        use_gpu: true
        abs_filepath: false
        filepath: sam_vit_b_cuda.torchscript
        img_width: 256
        img_height: 128
        h_fov: 1.5707
        v_fov: 0.7853
        min_range: 0.5
        max_range: 50.0
        num_prompts: 5
        visualize: true
