/**:
  ros__parameters:
    log_enabled:
      - lidar.perspective
      - navigation.sensor_input
      - tactic.pipeline
      - tactic.module
      - cbit.obstacle_filtering
      - lidar.obstacle_inflation

        # pose graph
      #- pose_graph

        # lidar pipeline
      - lidar.pipeline
      - torch
    tactic:
      localization_skippable: true
    pipeline:
      save_raw_point_cloud: True
      localization:
        - recall
        - icp
        - safe_corridor
        - segmentation
        - costmap_inflation
        - memory


    localization:
      segmentation:
        type: lidar.SAM
        use_gpu: true
        abs_filepath: false
        filepath: sam_vit_b_fast_cuda.torchscript
        img_width: 256
        img_height: 128
        h_fov: 1.5707
        v_fov: 0.7853
        min_range: 0.5
        max_range: 35.0
        num_prompts: 5
        smooth_size: 40
        iou_threshold: 1.0
        visualize: true
      costmap_inflation:
        type: lidar.costmap_queue
        influence_distance: 0.8 # was 0.5 Jordy # Note that the total distance where grid cells have values > 0 is min dist + influence dist, not influence dist!
        minimum_distance: 1.0 # was 0.3 Jordy
        resolution: 0.25
        costmap_history_size: 6
        neighbourhood: 5
        radius_filter: 0.5
        blind_spot_radius: 1.25
        lifetime: 1.5
        size_x: 16.0
        size_y: 8.0
        visualize: true
      fake_segmentation:
        type: lidar.TestObstacleModule
    path_planning:
      cbit:
        obstacle_avoidance: true
      mpc:
        homotopy_guided_mpc: false

