<?xml version="1.0"?>
<!--
Copyright (c) 2012, Siddhant Ahuja (Sid), Ryan Gariepy
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Clearpath Robotics nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

This program contains the description of the robot base model for the Clearpath Grizzly
-->

<robot xmlns:xi="http://www.w3.org/2001/XInclude"
       xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
       xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
       xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
       xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable"
       xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics"
       xmlns:xacro="http://ros.org/wiki/xacro"
       name="grizzly">

  <!-- Included URDF/XACRO Files -->
  <xacro:include filename="$(find grizzly_description)/urdf/materials.urdf.xacro" />
  <xacro:include filename="$(find grizzly_description)/urdf/wheel.urdf.xacro" />
  <xacro:include filename="$(find grizzly_description)/urdf/parts.urdf.xacro" />
  <xacro:include filename="$(find grizzly_description)/urdf/add_frame.urdf.xacro" />

  <!-- PROPERTY LIST -->
  <!--All units in m-kg-s-radians unit system -->
  <xacro:property name="M_PI"
            value="3.1415926535897931" />
  <!-- Main Body-base-->
  <!-- Location of com : center of mass -->
  <xacro:property name="base_x_com"
            value="-0.08748000" />
  <xacro:property name="base_y_com"
            value="-0.00085000" />
  <xacro:property name="base_z_com"
            value="0.09947000" />
  <!-- Size of the base-->
  <xacro:property name="base_x_size"
            value="0.708" />
  <xacro:property name="base_y_size"
            value="0.3" />
  <xacro:property name="base_z_size"
            value="1.826" />

  <!-- Mass of the base-->
  <xacro:property name="base_mass" value="487" />

  <!-- Mass of the front axle-->
  <xacro:property name="front_axle_mass" value="113" />

  <!--Inertial values for the front_axle at center of mass, aligned with coordinate system. Units are kg*m^2-->
  <xacro:property name="front_axle_ixx_com_cs"
            value="0.60216370" />
  <xacro:property name="front_axle_ixy_com_cs"
            value="-0.02364198" />
  <xacro:property name="front_axle_ixz_com_cs"
            value="-0.11972132" />
  <xacro:property name="front_axle_iyy_com_cs"
            value="1.73859574" />
  <xacro:property name="front_axle_iyz_com_cs"
            value="-0.00154437" />
  <xacro:property name="front_axle_izz_com_cs"
            value="2.02955229" />
  <!--Inertial values for the base at center of mass, aligned with coordinate system. Units are kg*m^2-->
  <xacro:property name="base_ixx_com_cs"
            value="0.60216370" />
  <xacro:property name="base_ixy_com_cs"
            value="-0.02364198" />
  <xacro:property name="base_ixz_com_cs"
            value="-0.11972132" />
  <xacro:property name="base_iyy_com_cs"
            value="1.73859574" />
  <xacro:property name="base_iyz_com_cs"
            value="-0.00154437" />
  <xacro:property name="base_izz_com_cs"
            value="2.02955229" />

  <!-- BASE-FOOTPRINT -->
  <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin, navigation stack depends on this frame -->
  <link name="base_footprint" />
  <gazebo reference="base_footprint">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>
  <joint name="base_footprint_joint"
         type="fixed">
    <origin xyz="0 0 ${wheel_x_size/2}"
            rpy="0 0 0" />
    <parent link="base_footprint" />
    <child link="base_link" />
  </joint>

  <!-- BASE-LINK -->
  <!--Actual body/chassis of the robot-->
  <link name="base_link">
    <inertial>
      <mass value="${base_mass}" />
      <!--This is the pose of the inertial reference frame, relative to the link reference frame. The origin of the inertial reference frame needs to be at the center of gravity. The axes of the inertial reference frame do not need to be aligned with the principal axes of the inertia.-->
      <origin xyz="${base_x_com} ${base_y_com} ${base_z_com}" />
      <!--The 3x3 rotational inertia matrix. Because the rotational inertia matrix is symmetric, only 6 above-diagonal elements of this matrix are specified here, using the attributes ixx, ixy, ixz, iyy, iyz, izz.-->
      <inertia ixx="${base_ixx_com_cs}"
               ixy="${base_ixy_com_cs}"
               ixz="${base_ixz_com_cs}"
               iyy="${base_iyy_com_cs}"
               iyz="${base_iyz_com_cs}"
               izz="${base_izz_com_cs}" />
    </inertial>
    <visual>
      <origin xyz="0 0 ${base_z_origin_offset}"
              rpy="${M_PI/2} 0 ${M_PI/2}" />
      <geometry>
        <mesh filename="package://grizzly_description/meshes/base_link.stl" />
      </geometry>
      <material name="DarkGrey" />
    </visual>
    <collision>
      <origin xyz="0 0 0.3"
              rpy="${M_PI/2} 0 ${M_PI/2}" />
      <geometry>
        <box size="${base_x_size} ${base_y_size} ${base_z_size}" />
        <!--making it slightly bigger in x and z direction-->
      </geometry>
    </collision>
  </link>
  <gazebo reference="base_link">
    <material>Gazebo/DarkGrey</material>
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>false</selfCollide>
  </gazebo>

  <!-- Add a sensor anchor link that points to the center of the robot top plate -->
  <xacro:grizzly_tf parent="base_link" name="sensor_anchor_link"
    translateX="0" translateY="0" translateZ="0.45"
    rotateX="0.0" rotateY="0.0" rotateZ="0.0"/>

  <!-- Add a sensor anchor link for the imu -->
  <xacro:grizzly_tf parent="sensor_anchor_link" name="imu_link"
    translateX="-0.788" translateY="0" translateZ="-0.118"
    rotateX="3.1415" rotateY="1.5701" rotateZ="0" />

  <!-- DECORATIONS -->
  <!-- Bumpers -->
  <xacro:grizzly_part parent="base_footprint"
                name="bumper"
                mesh="bumper"
                colour="Yellow"
                translateX="0.0"
                translateY="0.0"
                translateZ="0.5"
                rotateX="${M_PI/2}"
                rotateY="0.0"
                rotateZ="${M_PI/2}" />
  <gazebo reference="base_footprint_bumper_part">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <!-- Back wheels -->
  <xacro:grizzly_wheel fb="back"
                 lr="left"
                 parent="base_link"
                 translateX="-1.75"
                 translateY="1.75"
                 translateZ="0"
                 flipY="0" />
  <xacro:grizzly_wheel fb="back"
                 lr="right"
                 parent="base_link"
                 translateX="-1.75"
                 translateY="-1.75"
                 translateZ="0"
                 flipY="1" />

  <!-- Front axle link -->
  <joint name="front_axle_joint"
         type="revolute">
    <origin xyz="0.4375 0 0"
            rpy="0 0 0" />
    <parent link="base_link" />
    <child link="front_axle_link" />
    <axis xyz="1 0 0"
          rpy="0 0 0" />
    <limit effort="10"
           lower="-0.2"
           upper="0.2"
           velocity="0.5" />
  </joint>

  <link name="front_axle_link">
    <inertial>
      <mass value="${front_axle_mass}" />
      <origin xyz="0 0 0" />
      <inertia ixx="${front_axle_ixx_com_cs}"
               ixy="${front_axle_ixy_com_cs}"
               ixz="${front_axle_ixz_com_cs}"
               iyy="${front_axle_iyy_com_cs}"
               iyz="${front_axle_iyz_com_cs}"
               izz="${front_axle_izz_com_cs}" />
    </inertial>
    <visual>
      <origin xyz="-0.2 0 0.45"
              rpy="0 ${M_PI} ${M_PI/2}" />
      <geometry>
        <mesh filename="package://grizzly_description/meshes/front_axle.stl" />
      </geometry>
      <material name="DarkGrey" />
    </visual>
    <collision>
      <origin xyz="0 0 0"
              rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder length="1.0"
                  radius="0.13" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="front_axle_link">
    <material>Gazebo/DarkGrey</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <!-- Front wheels -->
  <xacro:grizzly_wheel fb="front"
                 lr="left"
                 parent="front_axle_link"
                 translateX="0"
                 translateY="1.75"
                 translateZ="0"
                 flipY="0" />
  <xacro:grizzly_wheel fb="front"
                 lr="right"
                 parent="front_axle_link"
                 translateX="0"
                 translateY="-1.75"
                 translateZ="0"
                 flipY="1" />

  <!-- Grizzly Plugin -->
  <gazebo>
    <plugin name="grizzly_diff_controller"
            filename="libgrizzly_gazebo_plugins.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
      <backLeftJoint>joint_back_left_wheel</backLeftJoint>
      <backRightJoint>joint_back_right_wheel</backRightJoint>
      <frontLeftJoint>joint_front_left_wheel</frontLeftJoint>
      <frontRightJoint>joint_front_right_wheel</frontRightJoint>
      <frontAxleJoint>front_axle_joint</frontAxleJoint>
      <wheelSeparation>${base_y_size}</wheelSeparation>
      <wheelDiameter>${wheel_x_size}</wheelDiameter>
      <torque>35</torque>
    </plugin>
  </gazebo>
</robot>
