# Unpublished Work Copyright 2019 Waymo LLC. All rights reserved.
# Waymo Proprietary and Confidential - Contains Trade Secrets

CXX = g++
CPPFLAGS=-I../include

LDLIBS=-lhoneycomb_c_api
LDFLAGS=-L../lib

all: hc_example hc_scanner hc_debug

clean:
	rm hc_example hc_scanner hc_debug

