uint8 ADD_RUN = 0
uint8 LOCALIZE = 1
uint8 START_MERGE = 2
uint8 CONFIRM_MERGE = 3
uint8 LOC_SEARCH = 4

# Action to be performed
uint8 action

# Target vertex, for LOCALIZE and START_MERGE
uint64 vertex

# Path, for START_MERGE
uint64[] path

---

# Success flag
bool success

# Error message
string message