uint8 VERTEX = 0
uint8 EDGE = 1

# Type of overlay requested
uint8 type

# What type of value do we want to get back?
string field
---
# List of vertex ids mapping to values, or pairs of vertex ids if this is an edge request
uint64[] ids
uint64[] to_ids

# Actual values for the overlay
float64[] values
