name: VTR Docker CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Pull the Docker image
        run: docker pull utiasasrl/vtr3:latest
      - name: run container
        run: docker run -td --name vtr3 --privileged -v `pwd`:/root/ASRL/vtr3/src:rw utiasasrl/vtr3:latest
      - name: colcon build
        run: docker exec -w /root/ASRL/vtr3/src/main vtr3 bash -c "source
          /opt/ros/humble/setup.sh && colcon build --symlink-install
          --cmake-args -DCMAKE_BUILD_TYPE=Release"
